---
title: "lab_2_634"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Question 1-2

```{r}
n = 12345
vec_1 = sample(12, n, replace = TRUE)
head(vec_1)
[1] 12  9  2  9  4  2


vec_2 = c(vec_1 ==3)
vec_1[vec_2]
```

#Question 3-5

n = 12345
vec_1 = sample(12,  n, replace = TRUE)
head(vec_1)

length(vec_1)

sum(vec_1 == 3)


> n = 10
> vec_1 = sample(12, n, replace = TRUE)
> paste0("Sum of elements with value 3: ", sum(vec_1 == 3))
[1] "Sum of elements with value 3: 2"
#I ran it again
[1] "Sum of  elements with value 3: 1"
# I ran it again
[1] "Sum of elements with value 3: 1"
#I ran it again
[1] "Sum of elements with value 3: 2"

#Question 6
```{r}
for (i in 1:10)
{
  print(i)
}


for (i in 1:10)
{
  print(paste0("This is loop iteration: ", i))
}
```


#Question 7
```{r}
for (i in 1:10)
{
  print(i)
}

n = sample(17, 1, replace = TRUE)
for (i in 1:n)
{
  print(i)
}
```


#Question 8
```{r}
n = 17
vec_1 = sample(10, n, replace = TRUE)

for (i in 1:n)
{
    print(paste0("The element of vec_1 at index: ", i, " is ", vec_1[i]))
}
```


# Question 9

```{r}
create_and_print_vec = function(n, min = 1, max = 10, na.rm = TRUE)
{
    vec_1 = sample(x = min:max, n, replace =
TRUE)
    for (i in 1:n)
    {
        print(paste0("The element of vec_1 at index: ", i, " is ", vec_1[i]))
    }
}

create_and_print_vec(10, min = 100, max = 2000)
```

